### ISSUE TITLE
[egui::Windows compatibility] Graph rendering stay on top of all egui::Windows 

### ISSUE THREAD

**Issue by deft01** [blitzarx1/egui_graphs#179]
Hi, 

Thanks a lot for the quick bug fix that makes compatibility with egui::Windows available.

I have discovered a new bug.

Graph rendering stay on top of all the egui::Windows  even if the Window where the graph is not focused.
I tested different configuration of GraphView, always with the same behavior.

![image](https://github.com/blitzarx1/egui_graphs/assets/10063471/5af6b458-b2ec-4e87-b7f5-6deaa603ab4e)

My versions (using last commit version on master) :

```toml
egui = "0.26.0"
egui_extras = { version = "0.26.0", features = ["svg", "image"]}
eframe = { version = "0.26.0", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
egui_tracing = "0.2.1"

serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"]}
ron = "0.8"
egui_graphs = { git = "https://github.com/blitzarx1/egui_graphs", branch = "master", features = ["egui_persistence", "serde"]}
```
