### ISSUE TITLE
Outdated crates.io version

### ISSUE THREAD

**Issue by wilfredjonathanjames** [blitzarx1/egui_graphs#186]
Thanks for such a great library. It's saving me some time. I just dropped in to say it looks like the crates.io version is out of date. In particular the `Graph::add_node*` interfaces are [missing](https://docs.rs/egui_graphs/0.19.0/egui_graphs/struct.Graph.html) though there may be some other things. Would you be able to bump the version and republish?

Until then I'm using the following:
```toml
#cargo.toml
...
[dependencies]
egui_graphs = { git = "https://github.com/blitzarx1/egui_graphs", res = "be8ae6aedeab950364ec67a2c2908345ccb5d8f2", version = "0.19.0" }
...
```

Cheers!
